name: Build and test

on:
  pull_request:
  push:
    branches:
      - ros2

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    container: ros:foxy

    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        path: 'planning_simulator_launcher'

    - name: Clone dependency packages
      run: |
        mkdir dependency_ws
        vcs import dependency_ws < planning_simulator_launcher/build_depends.repos

    - name: Upgrade ros packages
      run: |
        apt update
        apt upgrade -y

    - name: Install missing dependencies
      run: rosdep update && DEBIAN_FRONTEND=noninteractive rosdep install planning_simulator_launcher --from-paths . --ignore-src --rosdistro foxy -y

    - name: Build
      run: . /opt/ros/foxy/setup.sh && colcon build --event-handlers console_cohesion+ --packages-up-to planning_simulator_launcher

    - name: Run tests
      run: . /opt/ros/foxy/setup.sh && colcon test --event-handlers console_cohesion+ --packages-up-to planning_simulator_launcher
